### ISSUE TITLE
release cycle question

### ISSUE THREAD

**Issue by kewlfft** [rudimeier/twstools#11]
Hello
I don't see any release since 2014 while there has been quite a few commits, is there going to be a new release that could be used for a Linux package for example?
Thanks

**Comment by rudimeier** [comment]
Yeah *twstools* could need some updates. At the moment I'm working on support for the latest IB API version. When this is done I will probably release a minor update soon before doing other major changes.

**Comment by kewlfft** [comment]
ok thanks
